#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
"$ROOT/tests/test_janus_api.sh"
"$ROOT/tests/test_janus_config.sh"
"$ROOT/tests/test_janus_runtime.sh"
"$ROOT/tests/test_janus_ui.sh"
"$ROOT/tests/test_claude_launcher.sh"
"$ROOT/tests/test_codex_launcher.sh"
"$ROOT/tests/test_dispatcher.sh"
"$ROOT/tests/test_janus_control.sh"
"$ROOT/tests/test_install.sh"
python3 "$ROOT/tests/arrow_keys.py"
python3 "$ROOT/tests/api_key_setup.py"
python3 "$ROOT/tests/subagent_mapping.py"
python3 "$ROOT/tests/claude_initial_mapping.py"
python3 "$ROOT/tests/codex_first_run_setup.py"
python3 "$ROOT/tests/codex_model_selection.py"
python3 "$ROOT/tests/dispatcher_selection.py"
